[package]
name = "rust_02"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
prost = "0.7"
prost-types = { version = "0.7", optional = true }

[build-dependencies]
prost-build = "0.7"
